set nocompatible              " be iMproved
filetype off                  " required!
set t_Co=256                  " 256 colors

set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Plugin 'gmarik/vundle'

" git integration
Plugin 'tpope/vim-fugitive'
" a much simpler way to use some motions in vim
Plugin 'Lokaltog/vim-easymotion'
" statusline on steroids
Plugin 'bling/vim-airline'
" the NERDtree
Plugin 'scrooloose/nerdtree'
" improve '%' functionality like html-tag matching, if-else matching etc.
Plugin 'tmhedberg/matchit'
" golang integration
Plugin 'jnwhiteh/vim-golang'
" syntastic
Plugin 'scrooloose/syntastic'
" switch from .c to .h and vice versa easily
Plugin 'derekwyatt/vim-fswitch'

" vim-scripts repos
" Plugin 'L9'
" Plugin 'FuzzyFinder'

" non-GitHub repos
Plugin 'git://git.wincent.com/command-t.git'
" Git repos on your local machine (i.e. when working on your own lugin)
" Bundle 'file:///Users/gmarik/path/to/plugin'
" ...

filetype on
filetype plugin on
filetype plugin indent on     " required!

" Additional stuff
sy on
set bg=dark
set number
set laststatus=2                         " always show the statusline
set ttimeoutlen=50                       " fix statusbar lag when leaving insert mode
let g:NERDTreeDirArrows=0                " fix NERDTree's issue when trying to open a dir 
nmap <silent> <F3> :NERDTreeToggle<CR>   " map F3 to NERDTree toggle
nmap <silent> <F4> :FSHere<CR>           " map F4 to FSwitch toggle 
set backspace=indent,eol,start           " always enable to delete with backspace key in insert mode 
set colorcolumn=80                       " show 80 chars limit column

" tabs
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" syntastic
let g:syntastic_cpp_compiler="clang++"
let g:syntastic_cpp_compiler_options="-std=c++11 -stdlib=libc++"

" Improved tab navigation
nnoremap tq  :tabclose<CR>
nnoremap t<Left> :tabprev<CR>
nnoremap tt :tabnew<CR>
nnoremap t<Right> :tabnext<CR>

" improved splits navigation
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

"
" Brief help
" :PluginList          - list configured bundles
" :PluginInstall(!)    - install (update) bundles
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Plugin commands are not allowed.
